name: fashionation
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org. 
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^1.3.0
  page_transition: ^1.1.4
  flip_card: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/fashion_1.png
    - images/2.jpg
    - images/3.jpg
    - images/4.png
    - images/loginpic.png
    - images/logo1.png
    - images/logo2.png
    - images/andy_scott_1.png
    - images/1.jpg
    - images/pant1.png
    - images/shoes.png
    - images/shirt1.png
    - images/shirt2.png
    - images/belt.png
    - images/dressingtype1.jpg
    - images/dressingtype2.jpg
    - images/oval1.PNG
    - images/oval2.PNG
    - images/oval3.PNG
    - images/round1.PNG
    - images/round2.PNG
    - images/round3.PNG
    - images/square1.PNG
    - images/flipkart.jpg
    - images/myntra.jpg
    - images/amazon.jpg
    - images/flipkart.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Marker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
